@startuml
class User{

}
class Game{
    state
}
class GameStatistics{
    
}
class Player{
    username
    password
}
class PlayerStatistics{

}
class Profile{
    displayName
    profilePicture
}
class Round{
    nr
}
class Team{
    name
}

User <|-- Player
User <|-- Guest
User "0..*" -- "1..*" Game : plays
Player *-- Profile
Team -- User
Game o-- "20" Round
GameStatistics -- Game
PlayerStatistics -- Player
@enduml