.frontend_template: &frontend_configuration
  image: node:17-alpine
  before_script:
    - cd Frontend
    - npm ci --cache .npm --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

frontend_build:
  <<: *frontend_configuration
  stage: build
  script:
    - npm run build

frontend_lint:
  <<: *frontend_configuration
  stage: verify
  script:
    - npm run lint

qodana-js:
  <<: *frontend_configuration
  image:
    name: jetbrains/qodana-js:2021.3-eap
    entrypoint: ['']
  stage: verify
  script:
    - /opt/idea/bin/entrypoint --results-dir=$CI_PROJECT_DIR/qodana --save-report --report-dir=$CI_PROJECT_DIR/qodana/report
  artifacts:
    paths:
      - qodana/report/
    expose_as: 'Qodana JS Report'
