.frontend_template: &frontend_configuration
  image: node:17-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - cd Frontend

frontend_build:
  <<: *frontend_configuration
  stage: build
  script:
    - npm ci
    - npm run build

frontend_lint:
  <<: *frontend_configuration
  stage: verify
  script:
    - npm run lint
