.frontend_template: &frontend_configuration
  image: node:17-alpine
  before_script:
    - cd Frontend
    - npm ci --cache .npm --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

frontend_build:
  <<: *frontend_configuration
  stage: build
  script:
    - npm run build

frontend_lint:
  <<: *frontend_configuration
  stage: verify
  script:
    - npm run lint
