@startuml ContainerDiagram
!include <C4/C4_Container>

!include <material/vuejs>
!include <logos/kotlin>
!include <logos/postgresql>

title JassTracker - Container Diagram

Person(player, "Main Player", "Player with JassTracker")
System(jassTracker, "JassTracker", "Tool which tracks Jass scores")

System_Boundary(jassTracker, "JassTracker") {
    Container(frontend, "Frontend", "Vue.js, Vue Router, Pinia", "SPA, provides user interaction", $sprite="ma_vuejs")
    Container(backend, "Backend", "Kotlin, Ktor, jOOQ, Flyway", "Provides REST-API, handles business logic", $sprite="kotlin")
    ContainerDb(database, "Database", "PostgreSQL", "Stores persistent data", $sprite="postgresql")
}

Rel(player, frontend, "Interact with website", "HTTPS")
Rel(frontend, backend, "Sends API calls", "HTTPS/REST")
Rel_R(backend, database, "Reads and stores data")

@enduml
