@startuml ComponentDiagram
!include <C4/C4_Component>

!include <logos/postgresql>

title JassTracker - Component Diagram

Container_Boundary(frontend, "Frontend") {
    Component(components, "Components", "Vue Router", "Pages and user interface")
    Component(store, "Store", "Pinia", "Manage state and state updates")
    Component(backendApi, "Backend API", "mande", "Call backend API")
}

Container_Boundary(backend, "Backend") {
    Component(webApi, "Web API", "Ktor", "Routing and security")
    Component(domain, "Domain", "Plain Kotlin", "Business logic")
    Component(dataAccess, "Data Access", "jOOQ, Flyway", "Connect to DB")
    Component(bootstrap, "Bootstrap", "Ktor", "Bootstrap app")
}

ContainerDb(database, "Database", "PostgreSQL", "Stores persistent data", $sprite="postgresql")

Rel(components, store, "Send actions")
Rel(store, backendApi, "Trigger effect")
Rel_R(backendApi, webApi, "Calls", "HTTPS/REST")

Rel_R(webApi, domain, "Calls")
Rel_L(dataAccess, domain, "Provides services to")
Rel(dataAccess, database, "Reads and stores data")
Rel_D(bootstrap, webApi, "bootstraps")
Rel_D(bootstrap, dataAccess, "bootstraps")
Rel(bootstrap, domain, "bootstraps")

@enduml
