@startuml ComponentDiagram
!include <C4/C4_Component>

!include <logos/postgresql>

title JassTracker - Component Diagram

Container_Boundary(frontend, "Frontend") {
    Component(components, "Components", "", "Re-Usable Vue components")
    Component(views, "Views", "Vue Router", "Pages and user interface")
    Component(store, "Store", "Pinia", "Manage state and state updates")
    Component(backendApi, "Services", "mande", "Call backend API")
}

Container_Boundary(backend, "Backend") {
    Component(webApi, "Web API", "Ktor, kotlinx.serialization", "Routing and authentication")
    Component(domain, "Domain", "Plain Kotlin", "Business logic")
    Component(dataAccess, "Data Access", "jOOQ, Flyway", "Connect to DB")
    Component(bootstrap, "Bootstrap", "Ktor", "Bootstrap app, configure Ktor")
    Component(security, "Security", "Argon2, JWT", "Handle security critical sections")
}

ContainerDb(database, "Database", "PostgreSQL", "Stores persistent data", $sprite="postgresql")

Rel(views, components, "Uses")
Rel(views, store, "Sends actions")
Rel(store, backendApi, "Triggers effect")
Rel(backendApi, webApi, "Calls", "HTTPS/REST")

Rel(webApi, domain, "Calls")
Rel(dataAccess, domain, "Provides repositories")
Rel(security, domain, "Provides Token- & HashService")
Rel(dataAccess, database, "Reads and stores data")
Rel(bootstrap, webApi, "Bootstraps")
Rel(bootstrap, dataAccess, "Bootstraps")
Rel(bootstrap, security, "Bootstraps")

Rel(bootstrap, domain, "Bootstraps")

@enduml
