@startuml

!include <C4/C4_Deployment>

cloud Internet as internet {
}

cloud OST-Server {

  Node(proxy, "Proxy", "Traefik", "Reverse proxy, chooses container based on domain")

  Node(prod, "Production") {
    Container(jassProd, "JassTracker", "Ktor, jOOQ, Vue3", "Delivers the static Frontend and provides REST API.")
  }

  Node(test, "Test") {
    Container(jassTest, "JassTracker", "Ktor, jOOQ, Vue3", "Delivers the static Frontend and provides REST API.")
  }

  Node(postgres, "Postgres") {
    ContainerDb(dbProd, "prod", "JassTracker Schema")
    ContainerDb(dbTest, "staging", "JassTracker Schema")
  }
}

Rel(internet, proxy, "Uses JassTracker", "HTTPS")

Rel(proxy, prod, "Proxies requests to", "HTTP")
Rel(proxy, test, "Proxies requests to", "HTTP")

Rel(jassProd, dbProd, "Queries", "JDBC")
Rel(jassTest, dbTest, "Queries", "JDBC")

@endum
