/*
 * This file is generated by jOOQ.
 */
package dev.honegger.jasstracker.data.database.tables.records;


import dev.honegger.jasstracker.data.database.tables.GameParticipation;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameParticipationRecord extends UpdatableRecordImpl<GameParticipationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_participation.game_id</code>.
     */
    public void setGameId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.game_participation.game_id</code>.
     */
    public UUID getGameId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.game_participation.player_id</code>.
     */
    public void setPlayerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.game_participation.player_id</code>.
     */
    public UUID getPlayerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.game_participation.table_position</code>.
     */
    public void setTablePosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.game_participation.table_position</code>.
     */
    public Integer getTablePosition() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.game_participation.player_name</code>.
     */
    public void setPlayerName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.game_participation.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameParticipationRecord
     */
    public GameParticipationRecord() {
        super(GameParticipation.GAME_PARTICIPATION);
    }

    /**
     * Create a detached, initialised GameParticipationRecord
     */
    public GameParticipationRecord(UUID gameId, UUID playerId, Integer tablePosition, String playerName) {
        super(GameParticipation.GAME_PARTICIPATION);

        setGameId(gameId);
        setPlayerId(playerId);
        setTablePosition(tablePosition);
        setPlayerName(playerName);
        resetTouchedOnNotNull();
    }
}
