/*
 * This file is generated by jOOQ.
 */
package dev.honegger.jasstracker.database.tables.records;


import dev.honegger.jasstracker.database.tables.GameParticipation;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameParticipationRecord extends UpdatableRecordImpl<GameParticipationRecord> implements Record3<UUID, UUID, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_participation.game_id</code>.
     */
    public void setGameId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.game_participation.game_id</code>.
     */
    public UUID getGameId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.game_participation.player_id</code>.
     */
    public void setPlayerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.game_participation.player_id</code>.
     */
    public UUID getPlayerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.game_participation.table_position</code>.
     */
    public void setTablePosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.game_participation.table_position</code>.
     */
    public Integer getTablePosition() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return GameParticipation.GAME_PARTICIPATION.GAME_ID;
    }

    @Override
    public Field<UUID> field2() {
        return GameParticipation.GAME_PARTICIPATION.PLAYER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return GameParticipation.GAME_PARTICIPATION.TABLE_POSITION;
    }

    @Override
    public UUID component1() {
        return getGameId();
    }

    @Override
    public UUID component2() {
        return getPlayerId();
    }

    @Override
    public Integer component3() {
        return getTablePosition();
    }

    @Override
    public UUID value1() {
        return getGameId();
    }

    @Override
    public UUID value2() {
        return getPlayerId();
    }

    @Override
    public Integer value3() {
        return getTablePosition();
    }

    @Override
    public GameParticipationRecord value1(UUID value) {
        setGameId(value);
        return this;
    }

    @Override
    public GameParticipationRecord value2(UUID value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public GameParticipationRecord value3(Integer value) {
        setTablePosition(value);
        return this;
    }

    @Override
    public GameParticipationRecord values(UUID value1, UUID value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameParticipationRecord
     */
    public GameParticipationRecord() {
        super(GameParticipation.GAME_PARTICIPATION);
    }

    /**
     * Create a detached, initialised GameParticipationRecord
     */
    public GameParticipationRecord(UUID gameId, UUID playerId, Integer tablePosition) {
        super(GameParticipation.GAME_PARTICIPATION);

        setGameId(gameId);
        setPlayerId(playerId);
        setTablePosition(tablePosition);
    }
}
