/*
 * This file is generated by jOOQ.
 */
package dev.honegger.jasstracker.data.database.tables;


import dev.honegger.jasstracker.data.converters.LocalDateTimeConverter;
import dev.honegger.jasstracker.data.database.Keys;
import dev.honegger.jasstracker.data.database.Public;
import dev.honegger.jasstracker.data.database.tables.GameParticipation.GameParticipationPath;
import dev.honegger.jasstracker.data.database.tables.Player.PlayerPath;
import dev.honegger.jasstracker.data.database.tables.Table.TablePath;
import dev.honegger.jasstracker.data.database.tables.records.GameRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import kotlinx.datetime.LocalDateTime;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Game extends TableImpl<GameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game</code>
     */
    public static final Game GAME = new Game();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameRecord> getRecordType() {
        return GameRecord.class;
    }

    /**
     * The column <code>public.game.id</code>.
     */
    public final TableField<GameRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.game.start_time</code>.
     */
    public final TableField<GameRecord, LocalDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", new LocalDateTimeConverter());

    /**
     * The column <code>public.game.end_time</code>.
     */
    public final TableField<GameRecord, LocalDateTime> END_TIME = createField(DSL.name("end_time"), SQLDataType.LOCALDATETIME(6), this, "", new LocalDateTimeConverter());

    /**
     * The column <code>public.game.table_id</code>.
     */
    public final TableField<GameRecord, UUID> TABLE_ID = createField(DSL.name("table_id"), SQLDataType.UUID.nullable(false), this, "");

    private Game(Name alias, Table<GameRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Game(Name alias, Table<GameRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game</code> table reference
     */
    public Game(String alias) {
        this(DSL.name(alias), GAME);
    }

    /**
     * Create an aliased <code>public.game</code> table reference
     */
    public Game(Name alias) {
        this(alias, GAME);
    }

    /**
     * Create a <code>public.game</code> table reference
     */
    public Game() {
        this(DSL.name("game"), null);
    }

    public <O extends Record> Game(Table<O> path, ForeignKey<O, GameRecord> childPath, InverseForeignKey<O, GameRecord> parentPath) {
        super(path, childPath, parentPath, GAME);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GamePath extends Game implements Path<GameRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GamePath(Table<O> path, ForeignKey<O, GameRecord> childPath, InverseForeignKey<O, GameRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GamePath(Name alias, Table<GameRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GamePath as(String alias) {
            return new GamePath(DSL.name(alias), this);
        }

        @Override
        public GamePath as(Name alias) {
            return new GamePath(alias, this);
        }

        @Override
        public GamePath as(Table<?> alias) {
            return new GamePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GameRecord> getPrimaryKey() {
        return Keys.GAME_PKEY;
    }

    @Override
    public List<ForeignKey<GameRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GAME__GAME_TABLE_ID_FKEY);
    }

    private transient TablePath _table;

    /**
     * Get the implicit join path to the <code>public.table</code> table.
     */
    public TablePath table() {
        if (_table == null)
            _table = new TablePath(this, Keys.GAME__GAME_TABLE_ID_FKEY, null);

        return _table;
    }

    private transient GameParticipationPath _gameParticipation;

    /**
     * Get the implicit to-many join path to the
     * <code>public.game_participation</code> table
     */
    public GameParticipationPath gameParticipation() {
        if (_gameParticipation == null)
            _gameParticipation = new GameParticipationPath(this, null, Keys.GAME_PARTICIPATION__GAME_PARTICIPATION_GAME_ID_FKEY.getInverseKey());

        return _gameParticipation;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.player</code>
     * table
     */
    public PlayerPath player() {
        return gameParticipation().player();
    }

    @Override
    public Game as(String alias) {
        return new Game(DSL.name(alias), this);
    }

    @Override
    public Game as(Name alias) {
        return new Game(alias, this);
    }

    @Override
    public Game as(Table<?> alias) {
        return new Game(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(String name) {
        return new Game(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(Name name) {
        return new Game(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(Table<?> name) {
        return new Game(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Condition condition) {
        return new Game(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
