/*
 * This file is generated by jOOQ.
 */
package dev.honegger.jasstracker.data.database.enums;


import dev.honegger.jasstracker.data.database.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ContractType implements EnumType {

    acorns("acorns"),

    roses("roses"),

    shields("shields"),

    bells("bells"),

    tops_down("tops_down"),

    bottoms_up("bottoms_up"),

    joker("joker"),

    slalom("slalom"),

    guschti("guschti");

    private final String literal;

    private ContractType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "contract_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static ContractType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ContractType.class, literal);
    }
}
