name: JassTracker Backend

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 23
          cache: gradle
      - name: Verify
        run: ./gradlew --no-daemon check koverHtmlReport koverVerify
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/reports/kover/html/
