name: Dependency Review
on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v5
      with:
        retry-on-snapshot-warnings: true
        retry-on-snapshot-warnings-timeout: 600

