name: JassTracker Frontend

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: Frontend/package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: Frontend/pnpm-lock.yaml
      - run: pnpm i
        working-directory: Frontend
      - run: pnpm lint
        working-directory: Frontend
