name: Gradle Dependency Submission
on:
  push:
    branches:
      - main

jobs:
  gradle-action-detection:
    runs-on: ubuntu-latest
    # The Dependency Submission API requires write permission
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@main
        with:
          gradle-build-module: |-
            :Backend:bootstrap
          gradle-build-configuration: |-
            compileClasspath
          sub-module-mode: 'INDIVIDUAL_DEEP'
